name: Node & Nx Setup

description: Setup Nx CLI altogether with node

inputs:
  setup-node:
    default: "true"
    required: true
    description: Setup node

  setup-pnpm:
    default: "true"
    required: true
    description: Setup pnpm

  setup-nx:
    default: "true"
    required: true
    description: Setup Nx CLI

  pnpm-version:
    default: "10"
    required: true
    description: Pnpm version

  install-dependencies:
    default: "true"
    required: true
    description: Install dependencies

  nx-version:
    default: "20"
    required: true
    description: Nx version

  node-version:
    default: "22"
    description: Node version
    required: true

  node-cache:
    required: true
    default: pnpm
    description: Node cache

  node-cache-dependency-path:
    required: true
    default: package.json
    description: Node cache dependency path. This will be used to identify cached dependencies

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

    - name: Setup Node
      if: ${{ inputs.setup-node == 'true' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache }}
        cache-dependency-path: ${{ inputs.node-cache-dependency-path }}

    - name: Install dependencies
      shell: bash
      if: ${{ inputs.install-dependencies == 'true' }}
      run: pnpm install


    - name: Setup Nx
      if: ${{ inputs.setup-nx == 'true' }}
      shell: bash
      run: npm install -g nx@${{ inputs.nx-version }}
