name: Nx Docker Build & Push

description: Build and push Docker images using Nx and GCP Artifact Registry

inputs:
  plugin:
    required: true
    description: Nx plugin that is going to be run to build the images
    default: container

  run-affected:
    required: true
    default: 'true'
    description: Run only affected applications

  base-branch:
    required: true
    description: Base branch to check changed files

  application:
    required: true
    description: Name of the Nx application to build using target

  target:
    required: true
    description: Configuration name inside the plugin specified above for the specified application

  google-region:
    required: true
    description: GCP region (e.g. us-central1)

  google-credentials:
    required: true
    description: GCP service account key in JSON format

outputs:
  image:
    description: Image built and optionally pushed by this action
    value: ${{ inputs.image }}

runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        credentials_json: ${{ inputs.google-credentials }}

    - name: Docker Login to GCP Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.google-region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - uses: actions/checkout@v4

    - name: Build affected projects using Nx target
      if: ${{ inputs.run-affected == 'true' }}
      shell: bash
      run: nx affected --base=${{ inputs.base_branch }} --head=HEAD -t ${{ inputs.plugin }}:${{ inputs.target }}

    - name: Build affected projects using Nx target
      if: ${{ inputs.run-affected != 'true' }}
      shell: bash
      run: nx affected -t ${{ inputs.plugin }}:${{ inputs.target }}
