name: Docker login, build & push action
description: Docker composite that does the login into Google AR, builds and pushes the docker image to AR

inputs:
  image:
    required: true
    description: Docker image name
  
  context:
    required: true
    default: "."
    description: Docker build context
  
  dockerfile:
    required: true
    default: "Dockerfile"
    description: Dockerfile name & path

  args:
    required: true
    default: ""
    description: Docker args

  google-region: 
    required: true
    description: Google Project Region

runs:
  using: composite
  steps:
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v3'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ inputs.google-region }}-docker.pkg.dev'
    
    - name: Docker Build
      id: docker-build
      shell: bash
      run: |
        docker build ${{ inputs.args }} -t '${{ inputs.image }}' -f ${{ inputs.dockerfile }} ${{ inputs.context }}
        
        docker push '${{ inputs.image }}'